# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Feed:
    feed_id: int
    rss_url: str
    feed_name: str
    addition_date: datetime.datetime
    interval: datetime.timedelta
    last_completed: datetime.datetime
    consecutive_failures: int
    next_run: datetime.datetime


@dataclasses.dataclass()
class FeedHistory:
    history_id: int
    feed_id: int
    title: str
    link: str
    post_date: datetime.datetime
    collection_date: datetime.datetime
    unique_id: str


@dataclasses.dataclass()
class Subscription:
    subscriber_id: int
    feed_id: int
    subscription_time: datetime.datetime
    confirmation_code: float
    email: str
    signup_confirmed: bool
    last_post_notify: Optional[int]
    has_notification_pending: bool
