# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
import datetime


@dataclasses.dataclass()
class Feed:
    feed_id: int
    rss_url: str
    feed_name: str
    addition_date: datetime.datetime
    interval: datetime.timedelta
    last_completed: datetime.datetime
    last_update: datetime.datetime
    last_post_id: str
    last_notification_post_id: str
    last_post_pub: datetime.datetime
    last_notification_pub: datetime.datetime
    unresolved_notification: bool
    consecutive_failures: int
    next_run: datetime.datetime


@dataclasses.dataclass()
class Subscription:
    subscriber_id: int
    feed_id: int
    subscription_time: datetime.datetime
    confirmation_code: float
    email: str
    signup_confirmed: bool
    last_post_id: str
