# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
import datetime


@dataclasses.dataclass()
class Subscription:
    subscriber_id: int
    feed_id: int
    subscription_time: datetime.datetime
    confirmation_code: int
    email: str
    signup_confirmed: bool
