# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: queries.sql
from typing import Optional

import sqlalchemy

from . import models


GET_SUBSCRIPTION = """-- name: get_subscription \\:one
select subscriber_id, feed_id, subscription_time, confirmation_code, email, signup_confirmed from subscriptions
where subscriber_id = :p1 limit 1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_subscription(self, *, subscriber_id: int) -> Optional[models.Subscription]:
        row = self._conn.execute(sqlalchemy.text(GET_SUBSCRIPTION), {"p1": subscriber_id}).first()
        if row is None:
            return None
        return models.Subscription(
            subscriber_id=row[0],
            feed_id=row[1],
            subscription_time=row[2],
            confirmation_code=row[3],
            email=row[4],
            signup_confirmed=row[5],
        )
